apiVersion: apps/v1
kind: Deployment
metadata:
  name: team3-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team3-app
  template:
    metadata:
      labels:
        app: team3-app
    spec:
      containers:
      - name: team3-app
        image: sabry2os/team3-app:latest
        imagePullPolicy: IfNotPresent # Use 'IfNotPresent' or 'Always' for production
        ports:
        - containerPort: 5000